[package]
name = "signal-back"
version = "0.1.0"
authors = ["xeals <alex.smith@owari.cc>"]
build = "build.rs"

[dependencies]
byteorder = "1"
bytes = "0.4"
prost = "0.3"
prost-derive = "0.3"
rust-crypto = "0.2"

[build-dependencies]
prost-build = "0.3"
